name: GitHub Actions Mlops
on: [push]
jobs:
  _Build_and_Push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: Miyaaaaa/mlops:latest
      - run: docker build -t Miyaaaaa/mlops:latest .